name: Merge Schedule

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    # https://crontab.guru/every-hour
    - cron: "43 19 * * 0"

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v2.4.3
        with:
          # Merge method to use. Possible values are merge, squash or
          # rebase. Default is merge.
          merge_method: merge
          # Time zone to use. Default is UTC.
          time_zone: "Asia/Seoul"
          # Require all pull request statuses to be successful before
          # merging. Default is `false`.
          require_statuses_success: "false"
          # Label to apply to the pull request if the merge fails. Default is
          # `automerge-fail`.
          automerge_fail_label: "merge-schedule-failed"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
